// ng-cars/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { CarOwnerData } from '../model/carOwnerData';
import { IError } from '../model/interfaces';
import { CarOwnersService } from '../services/cars.service';
import { fail } from 'assert';

@Component({
  selector: 'app-cars',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'Cars & Owners';
  isLoading: Boolean = true;
  showError: IError;
  constructor(private _carService: CarOwnersService) { }

  ngOnInit() {
    this.showError = {
      message: '',
      show: false,
      onClose: this.hideError
    };
  }

  public setError = (error: { message: string, show: boolean }) => {
    this.showError.message = error.message;
    this.showError.show = error.show;
  }

  public setLoading = (loadStatus: boolean) => {
    this.isLoading = loadStatus;
  }

  public hideError = () => {
    this.showError.message = '';
    this.showError.show = false;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div class="conatiner">
  <div class="col-sm-6 col-sm-offset-1 col-xs-9 col-xs-offset-1">
    <h1>
      {{ title }}
    </h1>
    <app-cars-loader [componentLoading]="isLoading"></app-cars-loader>
    <app-cars-error [message]="showError.message" [show]="showError.show" [onClose]="showError.onClose"></app-cars-error>
    <app-cars-brand [setError]="setError" [setLoading]="setLoading"></app-cars-brand>
  </div>
</div>

// react-dotnet-cars/frontend/src/App.tsx
import * as React from 'react';
import { observable } from 'mobx';
import { observer } from 'mobx-react';
import { LoadingComponent, ErrorComponent, BrandComponent } from './components';

import './App.css';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import './assets/css/loading-bars.css';
import './assets/css/riliwan-rabo.css';
import { IError } from './model/interfaces';

@observer
class App extends React.Component<{}, {}> {
  @observable title: string = 'Cars & Owners';
  @observable isLoading: boolean = true;
  @observable showError: IError;
  constructor(props: any) {
    super(props);
    this.showError = { message: '', show: false, onClose: this.hideError };
  }

  render() {
    return (
      <div className="conatiner">
        <div className="col-sm-6 col-sm-offset-1 col-xs-9 col-xs-offset-1">
          <h1>{this.title}</h1>
          <LoadingComponent componentLoading={this.isLoading} />
          <ErrorComponent
            message={this.showError.message}
            show={this.showError.show}
            onClose={this.showError.onClose}
          />
          <BrandComponent setError={this.setError} setLoading={this.setLoading} />
        </div>
      </div>
    );
  }

  public setError = (error: { message: string, show: boolean }) => {
    this.showError.message = error.message;
    this.showError.show = error.show;
  }

  public setLoading = (loadStatus: boolean) => {
    this.isLoading = loadStatus;
  }

  public hideError = () => {
    this.showError.message = '';
    this.showError.show = false;
  }
}

export default App;
