// react-dotnet-cars/frontend/src/components/errors.component.tsx
import * as React from 'react';
import { observer } from 'mobx-react';

import { IError } from '../model/interfaces';

@observer
export class ErrorComponent extends React.Component<IError, {}> {

    constructor(props: IError) {
        super(props);
    }

    render() {
        return (
            <div className="container">
                <div className="alert alert-danger" hidden={!this.props.show}>
                    <button type="button" className="close" onClick={this.props.onClose}>&times;</button>
                    <strong>Error:</strong> {this.props.message}
                </div>
            </div>
        );
    }
}

// kloud-Test/ng-cars/src/app/directives/errors.component.ts
import { Component, Input } from '@angular/core';

import { IError } from '../../model/interfaces';

@Component({
    selector: 'app-cars-error',
    templateUrl: './errors.component.html'
})

export class ErrorComponent implements IError {
    @Input() message: string;
    @Input() show: boolean;
    @Input() onClose: () => void;
    constructor() {
        this.message = '';
        this.show = false;
    }
}
