// ng-cars/src/app/components/brands.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { CarOwnerData } from '../../model/carOwnerData';
import { IError, IOwnerColor } from '../../model/interfaces';
import { CarOwnersService } from '../../services/cars.service';

@Component({
    selector: 'app-cars-brand',
    templateUrl: './brands.component.html'
})

export class BrandComponent implements OnInit {
    @Input() setError: (error: { message: string, show: boolean }) => void;
    @Input() setLoading: (isLoading: boolean) => void;
    carBrands: string[] = [];
    constructor(private _carService: CarOwnersService) { }

    ngOnInit() {
        this.loadCars();
    }

    loadCars = async () => {
        this.setLoading(true);
        try {
            this.carBrands = await this._carService.getCarBrands();
        } catch (error) {
            this.setError({
                message: `Unable to read cars data. Please contact your Aadministrator`,
                show: true
            });
        }
        this.setLoading(false);
    }

    public getOwnersForBrand = async (brandName: string): Promise<IOwnerColor[]> => {
        try {
            return await this._carService.getOwnersByCarBrand(brandName);
        } catch (error) {
            this.setError({
                message: `Unable to read cars data. Please contact your Aadministrator`,
                show: true
            });
        }
    }
}

<div class="panel-group" >
    <div *ngFor="let brand of carBrands" class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">{{brand}}</h4>
        </div>
        <div>
            <app-cars-ownercolor [brandName]="brand"></app-cars-ownercolor>
        </div>
    </div>
</div>

// react-dotnet-cars/frontend/src/components/brands.component.tsx
import * as React from 'react';
import { observable } from 'mobx';
import { observer } from 'mobx-react';

import { IOwnerColor } from '../model/interfaces';
import CarOwnersService from '../store/cars.store';
import { OwnerColorComponent } from './owner.component';

export interface BrandProps {
    setError: (error: { message: string, show: boolean }) => void;
    setLoading: (isLoading: boolean) => void;
}

@observer
export class BrandComponent extends React.Component<BrandProps, {}> {
    @observable carBrands: string[] = [];
    constructor(props: BrandProps) {
        super(props);
        this.loadCars();
    }

    render() {
        let idx = 0;
        let carBrands = this.carBrands.map((car) => {
            return (
                <div key={idx++} className="panel panel-primary">
                    <div className="panel-heading">
                        <h4 className="panel-title">{car}</h4>
                    </div>
                    <OwnerColorComponent brandName={car} />
                </div>
            );
        });

        return (
            <div className="panel-group">
                {carBrands}
            </div>
        );
    }

    loadCars = async () => {
        this.props.setLoading(true);
        try {
            this.carBrands = await CarOwnersService.getCarBrands();
        } catch (error) {
            this.props.setError({
                message: `Unable to read cars data. Please contact your Aadministrator`,
                show: true
            });
        }
        this.props.setLoading(false);
    }

    public getOwnersForBrand = async (brandName: string): Promise<IOwnerColor[]> => {
        try {
            return await CarOwnersService.getOwnersByCarBrand(brandName);
        } catch (error) {
            this.props.setError({
                message: `Unable to read cars data. Please contact your Aadministrator`,
                show: true
            });
            return new Promise<any>((resolve, reject) => { reject('error getting brand owners'); });
        }
    }
}
