// react-dotnet-cars/frontend/src/components/loading.component.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
const loading = require('../assets/images/loading-bars.svg');

export interface LoadingProps {
    componentLoading: boolean;
}

@observer
export class LoadingComponent extends React.Component<LoadingProps, {}> {

    constructor(props: LoadingProps) {
        super(props);
    }

    render() {
        return (
            <div className="splash" hidden={!this.props.componentLoading}>
                <div className="color-line" />
                <div className="splash-title">
                    <img src={loading} width="64" height="64" />
                </div>
            </div>
        );
    }
}

// ng-cars/src/app/components/loading.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-cars-loader',
    templateUrl: './loading.component.html'
})

export class LoadingComponent {
    @Input() componentLoading: boolean;
    constructor() {
        this.componentLoading = false;
    }
}

<div class="splash" [hidden]="!componentLoading">
    <div class="color-line"></div>
    <div class="splash-title">
        <img src="assets/images/loading-bars.svg" width="64" height="64" />
    </div>
</div>
