// react-dotnet-cars/frontend/src/components/owner.component.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import { observable } from 'mobx';

import { IOwnerColor, IError } from '../model/interfaces';
import CarOwnersService from '../store/cars.store';
import { ErrorComponent } from './errors.component';

export interface OwnerProps {
    brandName: string;
}

@observer
export class OwnerColorComponent extends React.Component<OwnerProps, {}> {
    @observable owners: IOwnerColor[] = [];
    @observable showError: IError;
    @observable isLoading: Boolean = true;
    constructor(props: OwnerProps) { super(props); }

    componentWillMount() {
        this.showError = {
            show: false,
            message: '',
            onClose: this.hideError
        };
        this.loadOwners();
    }

    render() {
        let idx = 0;
        const ownerNames = this.owners.map((owner) => {
            idx++;
            return (
                <div key={idx} className="panel-collapse">
                    <div className="panel-body">{owner.name}</div>
                </div>
            );
        });
        return (
            <div>
                <ErrorComponent
                    message={this.showError.message}
                    show={this.showError.show}
                    onClose={this.showError.onClose}
                />
                {ownerNames}
            </div>
        );
    }

    public hideError = () => {
        this.showError.message = '';
        this.showError.show = false;
    }

    loadOwners = async () => {
        this.isLoading = true;
        try {
            this.owners = await CarOwnersService.getOwnersByCarBrand(this.props.brandName);
            this.owners = this.owners.filter((ownerColor) => ownerColor.name);
        } catch (error) {
            this.showError.message = 'Unable to get owner details. Please contact your administrator';
            this.showError.show = true;
        }
        this.isLoading = false;
    }
}

// ng-cars/src/app/components/owner.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { IOwnerColor, IError } from '../../model/interfaces';
import { CarOwnersService } from '../../services/cars.service';

@Component({
    selector: 'app-cars-ownercolor',
    templateUrl: './owner.component.html'
})

export class OwnerColorComponent implements OnInit {
    @Input() brandName: string;
    owners: IOwnerColor[] = [];
    showError: IError;
    isLoading: Boolean = true;
    constructor(private _carService: CarOwnersService) { }

    ngOnInit() {
        this.showError = {
            show: false,
            message: '',
            onClose: this.hideError
        };
        this.loadOwners();
    }

    public hideError = () => {
        this.showError.message = '';
        this.showError.show = false;
    }

    loadOwners = async () => {
        this.isLoading = true;
        try {
            this.owners = await this._carService.getOwnersByCarBrand(this.brandName);
            this.owners = this.owners.filter((ownerColor) => ownerColor.name );
        } catch (error) {
            this.showError.message = 'Unable to get owner details. Please contact your administrator';
            this.showError.show = true;
        }
        this.isLoading = false;
    }
}

<div>
    <app-cars-error [message]="showError.message" [show]="showError.show" [onClose]="showError.onClose"></app-cars-error>
    <div class="panel-collapse" *ngFor="let owner of owners">
        <div class="panel-body">{{owner.name}}</div>
    </div>
</div>
